PARTIDOS_TSE = [
  { label: "MDB", name: "Movimento Democrático Brasileiro", number: 15, registered_on: "1981-06-30", former_labels: "PMDB" },
  { label: "PDT", name: "Partido Democrático Trabalhista", number: 12, registered_on: "1981-11-10" },
  { label: "PT", name: "Partido dos Trabalhadores", number: 13, registered_on: "1982-02-11" },
  { label: "PCdoB", name: "Partido Comunista do Brasil", number: 65, registered_on: "1988-06-23" },
  { label: "PSB", name: "Partido Socialista Brasileiro", number: 40, registered_on: "1988-07-01" },
  { label: "PSDB", name: "Partido da Social Democracia Brasileira", number: 45, registered_on: "1989-08-24" },
  { label: "AGIR", name: "Agir", number: 36, registered_on: "1990-02-22", former_labels: "PTC PRN" },
  { label: "MOBILIZA", name: "Mobilização Nacional", number: 33, registered_on: "1990-10-25", former_labels: "PMN" },
  { label: "CIDADANIA", name: "Cidadania", number: 23, registered_on: "1992-03-19", former_labels: "PPS" },
  { label: "PV", name: "Partido Verde", number: 43, registered_on: "1993-09-30" },
  { label: "AVANTE", name: "Avante", number: 70, registered_on: "1994-10-11", former_labels: "PTdoB" },
  { label: "PP", name: "Progressistas", number: 11, registered_on: "1995-11-16", former_labels: "PPB PPR" },
  { label: "PSTU", name: "Partido Socialista dos Trabalhadores Unificado", number: 16, registered_on: "1995-12-19" },
  { label: "PCB", name: "Partido Comunista Brasileiro", number: 21, registered_on: "1996-05-09" },
  { label: "PRTB", name: "Partido Renovador Trabalhista Brasileiro", number: 28, registered_on: "1997-02-18" },
  { label: "DC", name: "Democracia Cristã", number: 27, registered_on: "1997-08-05", former_labels: "PSDC" },
  { label: "PCO", name: "Partido da Causa Operária", number: 29, registered_on: "1997-09-30" },
  { label: "PODE", name: "Podemos", number: 20, registered_on: "1997-10-02", former_labels: "PTN PHS PSC" },
  { label: "REPUBLICANOS", name: "Republicanos", number: 10, registered_on: "2005-08-25", former_labels: "PRB PMR" },
  { label: "PSOL", name: "Partido Socialismo e Liberdade", number: 50, registered_on: "2005-09-15" },
  { label: "PL", name: "Partido Liberal", number: 22, registered_on: "2006-12-19", former_labels: "PR PRONA" },
  { label: "PSD", name: "Partido Social Democrático", number: 55, registered_on: "2011-09-27" },
  { label: "SOLIDARIEDADE", name: "Solidariedade", number: 77, registered_on: "2013-09-24", former_labels: "SD PROS" },
  { label: "NOVO", name: "Partido Novo", number: 30, registered_on: "2015-09-15" },
  { label: "REDE", name: "Rede Sustentabilidade", number: 18, registered_on: "2015-09-22" },
  { label: "DEMOCRATA", name: "Democrata", number: 35, registered_on: "2015-09-29", former_labels: "PMB" },
  { label: "UP", name: "Unidade Popular", number: 80, registered_on: "2019-12-10" },
  { label: "UNIÃO", name: "União Brasil", number: 44, registered_on: "2022-02-08", former_labels: "PSL DEM PFL" },
  { label: "PRD", name: "Partido Renovação Democrática", number: 25, registered_on: "2023-11-09", former_labels: "PTB PATRIOTA PATRI PEN" },
  { label: "MISSÃO", name: "Partido Missão", number: 14, registered_on: "2025-11-04" }
]

# Extintos por fusão ou incorporação: ver Party::MERGERS
